### ISSUE TITLE
House Protection not working for doors

### ISSUE THREAD

**Issue by Maenso** [CoderCow/HouseRegions-Plugin#13]
The defined area gets protected but when i hit a door with a pickaxe it simply gets destroyed after a message: "This region is protected from changes"

**Comment by CoderCow** [comment]
Because some of the tiles of the door are - when it is opened - outside the actual house region, so it can be hit without protection.

Tell the people on your server to make their house regions one block larger than their actual house is, this will also prevent people from placing torches or blocks on the sides of their houses.
